"use strict";
exports.__esModule = true;
var IProductApi_1 = require("../services/IProductApi");
var product = new IProductApi_1.ProductApi();
console.log(product.findByCategory("tablet"));
// console.log(product.findAll());
// console.log(product.findByText("black"));
// console.log(product.findCheapestProduct());
// console.log(product.findStockCountMax20());
// console.log(product.searchByBrandName("HP"));
